
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
//import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
   
    public Customer() {
        this.setResizable(false);
        
        initComponents();
        
        conn = db_connect.connectDB();
        
        
       this.Update_table();
    }
    
     public void Update_table(){
    try{
        String sql = "SELECT * FROM customer";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        cus.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(Exception e){
      //  JOptionPane.showMessageDialog(null, e);
    
    }finally{
    
        try{
        rs.close();
        pst.close();
        }
        
        catch(Exception e){
            
        }
    }
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cust = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cus = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tot1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        oId1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setForeground(new java.awt.Color(255, 51, 51));
        setMinimumSize(new java.awt.Dimension(1331, 855));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1699, 192, 65, 29);

        cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custActionPerformed(evt);
            }
        });
        getContentPane().add(cust);
        cust.setBounds(190, 270, 260, 40);

        cus.setBackground(new java.awt.Color(204, 204, 204));
        cus.setFont(new java.awt.Font("Algerian", 0, 13)); // NOI18N
        cus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order Id", "cusId", "Table No.", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cus);
        if (cus.getColumnModel().getColumnCount() > 0) {
            cus.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 120, 830, 580);

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Algerian", 0, 13)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(460, 730, 150, 50);

        search.setBackground(new java.awt.Color(51, 102, 255));
        search.setFont(new java.awt.Font("Algerian", 0, 13)); // NOI18N
        search.setText("Search by order Id");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(90, 40, 200, 40);

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Algerian", 0, 13)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(680, 730, 150, 50);

        tNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNoActionPerformed(evt);
            }
        });
        getContentPane().add(tNo);
        tNo.setBounds(190, 340, 260, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Table No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 340, 90, 29);

        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1);
        s1.setBounds(300, 40, 260, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bill Total");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 410, 90, 29);

        tot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tot1ActionPerformed(evt);
            }
        });
        getContentPane().add(tot1);
        tot1.setBounds(190, 410, 260, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer Id");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 270, 120, 40);

        oId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oId1ActionPerformed(evt);
            }
        });
        getContentPane().add(oId1);
        oId1.setBounds(190, 200, 260, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Order Id");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 200, 120, 40);

        jButton4.setBackground(new java.awt.Color(51, 102, 255));
        jButton4.setFont(new java.awt.Font("Algerian", 0, 13)); // NOI18N
        jButton4.setText("REMOVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(890, 730, 150, 50);

        jButton5.setBackground(new java.awt.Color(51, 102, 255));
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(50, 760, 70, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey-Background-7.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 1340, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        
          try{
               String val  = oId1.getText();
            String val1 = cust.getText();
            String val2 = tNo.getText();
            String val3 = tot1.getText();
          
          
           // String sql = "UPDATE `cust` SET `cId` = '"+val1+"', `table` ='"+val2+"',`total` = '"+val3+"', WHERE `orderId` = '"+val+"'"; 
            
         Statement stmt = conn.createStatement();
           stmt.execute("UPDATE `customer` SET `cId` = '"+val1+"', `table` ='"+val2+"', `total` ='"+val3+"' WHERE `orderId` = '"+val+"'");
            JOptionPane.showMessageDialog(null, "Record Updated!!");
        
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }finally{
        
        }try{
        
        }catch(Exception e){
        
        }
        this.Update_table();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    // TODO add your handling code here:
        try{

            String sql ="select * from customer where orderId=? ";

            pst = conn.prepareStatement(sql);
            pst.setString(1,s1.getText());
            
            rs = pst.executeQuery();
            if (rs.next()){
            
                String add1 =rs.getString("orderId");
                oId1.setText(add1);

                String add2 =rs.getString("cId");
                cust.setText(add2);

                String add3 =rs.getString("table");
                tNo.setText(add3);

                String add4 =rs.getString("total");
                tot1.setText(add4);
               
            }

        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String order= oId1.getText();
        String cId = cust.getText();
        String tableNo = tNo.getText();
        String total = tot1.getText();
         
         if(order.equals("")){
            JOptionPane.showMessageDialog(null, "Fill Order Id field");
        }
        if(cId.equals("")){
            JOptionPane.showMessageDialog(null, "Fill Customer Id field");
        }
       if(tableNo.equals("")){
            JOptionPane.showMessageDialog(null, "Fill table Number field");
        }
       if(total.equals("")){
            JOptionPane.showMessageDialog(null, "Fill Total field");
        }
       
       
      
        
        try{
            String q = "INSERT INTO customer VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(q);
            
            pst.setString(1,order);
            pst.setString(2,cId);
            pst.setString(3,tableNo);
            pst.setString(4,total);
 
            
            
         //   JOptionPane.showMessageDialog(null, "Data is saved successsully!!");
            pst.executeUpdate();
        
        }catch(Exception e){
           // JOptionPane.showMessageDialog(null, e);
        }
       
        this.Update_table();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void tot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tot1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
          int x = JOptionPane.showConfirmDialog(null, "Are you Sure you want to delete this record???", "Add Record", JOptionPane.YES_NO_OPTION);
        if(x == 0){    
        try{
            String sql ="delete from customer where orderId=? ";
            
                pst=conn.prepareStatement(sql);
                pst.setString(1, s1.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
            try{

                String sq ="delete from customer where orderId=?";
                pst=conn.prepareStatement(sq);
                pst.setString(1, s1.getText());
                pst.execute();

            }catch(Exception e){

            }
        }
        this.Update_table();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
                    Home  j = new Home();
                    j.setVisible(true);
                    this.dispose();
            

        }catch (Exception e){

         //   JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custActionPerformed

    private void oId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oId1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cus;
    private javax.swing.JTextField cust;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField oId1;
    private javax.swing.JTextField s1;
    private javax.swing.JButton search;
    private javax.swing.JTextField tNo;
    private javax.swing.JTextField tot1;
    // End of variables declaration//GEN-END:variables
}
