
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class inventory extends javax.swing.JFrame {

    /**
     * Creates new form inventory
     */
     Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs=null;
   
    public inventory() {
        this.setResizable(false);
        
        initComponents();
        
        conn = db_connect.connectDB();
        
        
       this.Update_table();
       this.Update_table2();
    }
    
     public void Update_table(){
    try{
        String sql = "SELECT * FROM veg";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        vege.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    
    }finally{
    
        try{
        rs.close();
        pst.close();
        }
        
        catch(Exception e){
            
        }
    }
  }
    public void Update_table2(){
    try{
        String sql = "SELECT * FROM fruit";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        fr.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    
    }finally{
    
        try{
        rs.close();
        pst.close();
        }
        
        catch(Exception e){
            
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        q = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vege = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        name2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        q2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        fr = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        it1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        it2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 146, -1, -1));
        getContentPane().add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 185, 97, 30));

        vege.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vege);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, 468));

        jLabel12.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Vegetables");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 25, 169, 43));
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 164, 266, 30));

        jLabel13.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel13.setText("fruits");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 25, 169, 43));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Item Id");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 146, 266, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Quantity");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 214, -1, -1));
        getContentPane().add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 208, 97, 30));

        fr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(fr);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, 468));

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 194, -1, -1));

        it1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                it1ActionPerformed(evt);
            }
        });
        getContentPane().add(it1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 105, 97, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Item Id");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 111, -1, -1));
        getContentPane().add(it2, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 116, 97, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 164, -1, -1));

        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 207, -1, -1));

        jButton4.setText("Remove");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 266, 86, 39));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 266, 86, 39));

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, -1, -1));

        jButton6.setText("Remove");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, -1, -1));

        jButton7.setText("Search by Id");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 273, -1, -1));

        jButton8.setText("Search by Id");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 273, -1, -1));

        jButton9.setText("BACK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 820, -1, -1));

        jButton10.setText("NEXT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 820, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Quantity");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 191, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("kg");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("kg");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Grey-Background-7.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 940));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String item = it1.getText();
        String n2 = name.getText();
        String quant = q.getText();
        
        if(item.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Item Number");
        }
        if(n2.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Item Name");
        }
       if(quant.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Quantity");
        }
         
      
        
        try{
            String q = "INSERT INTO veg VALUES (?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(q);
            
            pst.setString(1,item);
            pst.setString(2,n2);
            pst.setString(3,quant);
            ;
 
            
            
           // JOptionPane.showMessageDialog(null, "Data is saved successsully!!");
            pst.executeUpdate();
        
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }
       
        this.Update_table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            String item2 = it2.getText();
        String n2 = name2.getText();
        String quant2 = q2.getText();
        if(item2.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Item Number");
        }
        if(n2.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Item Name");
        }
       if(quant2.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Quantity");
        }
       
         
      
        
        try{
            String q = "INSERT INTO fruit VALUES (?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(q);
            
            pst.setString(1,item2);
            pst.setString(2,n2);
            pst.setString(3,quant2);
            ;
 
            
            
          //  JOptionPane.showMessageDialog(null, "Data is saved successsully!!");
            pst.executeUpdate();
        
        }catch(Exception e){
           // JOptionPane.showMessageDialog(null, e);
        }
       
        this.Update_table2();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void it1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_it1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_it1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
          try{
               String val  = it1.getText();
            String val1 = name.getText();
            String val2 = q.getText();
            
          
          
           // String sql = "UPDATE `cust` SET `cId` = '"+val1+"', `table` ='"+val2+"',`total` = '"+val3+"', WHERE `orderId` = '"+val+"'"; 
            
         Statement stmt = conn.createStatement();
            stmt.execute("UPDATE `veg` SET `name` = '"+val1+"', `quant` ='"+val2+"' WHERE `itemId` = '"+val+"'");
            JOptionPane.showMessageDialog(null, "Record Updated!!");
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally{
        
        }try{
        
        }catch(Exception e){
        
        }
        this.Update_table();
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int x = JOptionPane.showConfirmDialog(null, "Are you Sure you want to delete this record???", "Add Record", JOptionPane.YES_NO_OPTION);
        if(x == 0){    
        try{
            String sql ="delete from veg where itemId=? ";
            
                pst=conn.prepareStatement(sql);
                pst.setString(1, jTextField1.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
            try{

                String sq ="delete from veg where itemId=?";
                pst=conn.prepareStatement(sq);
                pst.setString(1, jTextField1.getText());
                pst.execute();

            }catch(Exception e){

            }
        }
        this.Update_table();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try{
               String val  = it2.getText();
            String val1 = name2.getText();
            String val2 = q2.getText();
            
          
          
           // String sql = "UPDATE `cust` SET `cId` = '"+val1+"', `table` ='"+val2+"',`total` = '"+val3+"', WHERE `orderId` = '"+val+"'"; 
            
         Statement stmt = conn.createStatement();
            stmt.execute("UPDATE `fruit` SET `name` = '"+val1+"', `quant` ='"+val2+"' WHERE `itemId` = '"+val+"'");
            JOptionPane.showMessageDialog(null, "Record Updated!!");
        
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, e);
        }finally{
        
        }try{
        
        }catch(Exception e){
        
        }
        this.Update_table2();
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         int x = JOptionPane.showConfirmDialog(null, "Are you Sure you want to delete this record???", "Add Record", JOptionPane.YES_NO_OPTION);
        if(x == 0){    
        try{
            String sql ="delete from fruit where itemId=? ";
            
                pst=conn.prepareStatement(sql);
                pst.setString(1, jTextField2.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null,"Record Deleted");

            }catch(Exception e){

                //JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
            try{

                String sq ="delete from fruit where itemId=?";
                pst=conn.prepareStatement(sq);
                pst.setString(1, jTextField2.getText());
                pst.execute();

            }catch(Exception e){

            }
        }
        this.Update_table2();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{

            String sql ="select * from veg where itemId=? ";

            pst = conn.prepareStatement(sql);
            pst.setString(1,jTextField1.getText());
            
            rs = pst.executeQuery();
            if (rs.next()){
            
                String add1 =rs.getString("itemId");
                it1.setText(add1);

                String add2 =rs.getString("name");
                name.setText(add2);

                String add3 =rs.getString("quant");
                q.setText(add3);

               
            }

        }catch(Exception e){
           // JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         try{

            String sql ="select * from fruit where itemId=? ";

            pst = conn.prepareStatement(sql);
            pst.setString(1,jTextField2.getText());
            
            rs = pst.executeQuery();
            if (rs.next()){
            
                String add1 =rs.getString("itemId");
                it2.setText(add1);

                String add2 =rs.getString("name");
                name2.setText(add2);

                String add3 =rs.getString("quant");
                q2.setText(add3);

               
            }

        }catch(Exception e){
          //  JOptionPane.showMessageDialog(null, e);
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(Exception e){

            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
             try{
                    Home  j = new Home();
                    j.setVisible(true);
                    this.dispose();
            

        }catch (Exception e){

           // JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try{
                    Others j = new Others();
                    j.setVisible(true);
                    this.dispose();
            

        }catch (Exception e){

          //  JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fr;
    private javax.swing.JTextField it1;
    private javax.swing.JTextField it2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField q;
    private javax.swing.JTextField q2;
    private javax.swing.JTable vege;
    // End of variables declaration//GEN-END:variables
}
